apiVersion: v1
kind: Service
metadata:
  name: ollama-qwen-service
  labels:
    app: ollama-qwen-app
spec:
  selector:
    app: ollama-qwen-app
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
